# Generated by Django 2.2.5 on 2019-10-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_tool_lead_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='Hub',
            new_name='City',
        ),
    ]
