# Generated by Django 2.2.1 on 2019-11-09 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_tool_lead_manager_app', '0002_auto_20191023_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_leads_created_at', models.DateTimeField(auto_now_add=True)),
                ('company_leads_corporate_hub', models.CharField(max_length=264)),
                ('company_leads_company_name', models.CharField(max_length=264)),
                ('company_leads_employee_strength', models.CharField(max_length=264)),
                ('company_leads_contact_person', models.CharField(max_length=264)),
                ('company_leads_contact_mobile', models.CharField(max_length=264)),
                ('company_leads_contact_email', models.CharField(max_length=264)),
                ('company_leads_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_leads_login_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tool_lead_manager_app.Login_Time')),
                ('company_leads_logout_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tool_lead_manager_app.Logout_Time')),
                ('company_leads_pickup_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tool_lead_manager_app.Pickup_Location')),
            ],
        ),
        migrations.CreateModel(
            name='Lead_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_comment_name', models.CharField(choices=[('Interested', 'Interested'), ('Undecided', 'Undecided'), ('Uncontacted', 'Uncontacted'), ('Converted', 'Converted')], max_length=264)),
                ('lead_comment_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_comment_remark', models.TextField(blank=True, max_length=264)),
                ('lead_comment_product_interested_in', models.CharField(choices=[('Nodal Service', 'Nodal Service'), ('Hub Cab', 'Hub Cab'), ('Others', 'Others')], default='Not Selected', max_length=264)),
                ('lead_comment_next_followup_date', models.DateField(max_length=264)),
                ('lead_comment_updated', models.DateTimeField(auto_now=True)),
                ('lead_comment_Created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_comment_Updated_at', models.DateTimeField(auto_now=True)),
                ('lead_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tool_lead_manager_app.Leads')),
                ('lead_comment_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Comment',
                'verbose_name_plural': 'Leads Comment',
            },
        ),
        migrations.CreateModel(
            name='Company_Leads_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_lead_comment_name', models.CharField(choices=[('Interested', 'Interested'), ('Undecided', 'Undecided'), ('Uncontacted', 'Uncontacted'), ('Converted', 'Converted')], max_length=264)),
                ('company_lead_comment_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_lead_comment_remark', models.TextField(blank=True, max_length=264)),
                ('company_lead_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tool_lead_manager_app.Company_Leads')),
                ('company_lead_comment_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
