# Generated by Django 2.2.1 on 2019-11-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_tool_lead_manager_app', '0003_company_leads_company_leads_comment_lead_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_leads',
            name='company_leads_designation',
            field=models.CharField(default='', max_length=264),
        ),
    ]
