# Generated by Django 2.2.1 on 2019-11-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_tool_lead_manager_app', '0004_company_leads_company_leads_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='Login_Time_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location', to='marketing_tool_lead_manager_app.Login_Time'),
        ),
    ]
